version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=dev123

# docker-compose exec db psql -U myuser -d mydatabase
# entering into db using docker

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:dev123@db:5432/database

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3002:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
